version: '3'

services:
  xciot-ap:
    build: ./ap
    container_name: xciot-ap
    ports:
      - 80:8080
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./ap/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./ap/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./ap/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./ap/webapps/xcent.war:/usr/local/tomcat/webapps/xcent.war
      # - /opt/xcent:/opt/xcent
      # - /opt/xcent/tomcat/logs:/usr/local/tomcat/logs
    